name: pr-close

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_API_CLIENT_ID: ${{ secrets.AUTH0_API_CLIENT_ID }}
      AUTH0_API_CLIENT_SECRET: ${{ secrets.AUTH0_API_CLIENT_SECRET }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CALLBACK_URL: https://pr%d.example.com
    steps:
      - name: Update Auth0
        run: |
          set -o pipefail
          ACCESS_TOKEN=$(curl -f -s --request POST \
            --url "https://${AUTH0_DOMAIN}/oauth/token" \
            --header 'content-type: application/x-www-form-urlencoded' \
            --data grant_type=client_credentials \
            --data "client_id=${AUTH0_API_CLIENT_ID}" \
            --data "client_secret=${AUTH0_API_CLIENT_SECRET}" \
            --data "audience=https://${AUTH0_DOMAIN}/api/v2/" | jq -r .access_token)
          echo "The request access token was succeeded"
          CALLBACKS=$(curl -f -s -H "Authorization: Bearer ${ACCESS_TOKEN}" "https://${AUTH0_DOMAIN}/api/v2/clients/${AUTH0_CLIENT_ID}" | jq -c .callbacks)
          CALLBACK_URL=$(printf "${AUTH0_CALLBACK_URL}" $(jq -r .pull_request.number "$GITHUB_EVENT_PATH"))
          if [ $(echo ${CALLBACKS} | jq "index(\"${CALLBACK_URL}\")") = null ]; then
            echo The callback URL was already removed
            exit 0
          fi
          curl -f -X PATCH -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "Content-Type: application/json" -d "{\"callbacks\":$(echo ${CALLBACKS} | jq -c ". -= [\"${CALLBACK_URL}\"]")}" "https://${AUTH0_DOMAIN}/api/v2/clients/${AUTH0_CLIENT_ID}" >/dev/null
          echo The callback URL removal was succeeded
