name: pr-close

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  remove-review-app-config:
    runs-on: ubuntu-latest
    steps:
      - name: remove review app config
        uses: 'autopp/action-auth0-update-client@v1'
        with:
          domain: ${{ secrets.AUTH0_DOMAIN }}
          api_client_id: ${{ secrets.AUTH0_API_CLIENT_ID }}
          api_client_secret: ${{ secrets.AUTH0_API_CLIENT_SECRET }}
          operation: remove
          client_id: ${{ secrets.AUTH0_CLIENT_ID }}
          callback_url: ${{ format('https://pr{0}.example.com/auth/auth0/callback', github.event.pull_request.number) }}
          logout_url: ${{ format('https://pr{0}.example.com', github.event.pull_request.number) }}
