name: pr-open

on:
  pull_request:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
    steps:
      - name: get pr number
        run: |
          jq . "$GITHUB_EVENT_PATH"
          jq -r .pull_request.number "$GITHUB_EVENT_PATH"
      - name: Update Auth0
        run: |
          ACCESS_TOKEN=$(curl --request POST \
            --url "https://${AUTH0_DOMAIN}/oauth/token" \
            --header 'content-type: application/x-www-form-urlencoded' \
            --data grant_type=client_credentials \
            --data "client_id=${AUTH0_CLIENT_ID}" \
            --data "client_secret=${AUTH0_CLIENT_SECRET}" \
            --data "audience=https://${AUTH0_DOMAIN}/api/v2/" | jq -r .access_token)
          test -n "${ACCESS_TOKEN}"
