name: pr-open

on:
  pull_request:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: get pr number
        run: |
          jq . "$GITHUB_EVENT_PATH"
          jq -r .pull_request.number "$GITHUB_EVENT_PATH"
